### PR TITLE
BOT API v7.0

### PR DESCRIPTION
**Pull request by mircoianese**
**Still a Work In progress.** 

- [x] Reactions (done by [@anfanik](https://github.com/anfanik) in #353)
- [x] Replies 2.0
- [x] Link Preview Customization
- [x] Block Quotation
- [x] Multiple Message Actions
- [x] Request for multiple users
- [x] Chat Boost
- [x] Giveaway
- [x] Web App Changes 
- [x] Other Changes

Will try to finish the remaining by the end of the week.

### CODE REVIEW

**Comment by mircoianese** [comment]
Merged PR #354 into master to align this PR with those changes.

**Comment by anfanik** [comment]
I've implemented Chat Boost and Other Changes parts.

https://github.com/mircoianese/java-telegram-bot-api/pull/1

**Comment by mircoianese** [comment]
There are a lot of changes and possibly something will break. 
But should be ready for review @pengrad 

Thanks @anfanik !

**Comment by anfanik** [comment]
You're welcome! @mircoianese
I tried to maintain backward compatibility in my commits

**Review by pengrad — APPROVED** [review]

**Pull request merged**
