### PR TITLE
BOT API v7.4

### PR DESCRIPTION
**Pull request by mircoianese**
Need to update the BOT API from v7.2 to v7.4 (released today, [changelog](https://core.telegram.org/bots/api-changelog#may-28-2024)).

Here's the task to be done, please write a comment if you plan to help on some features.
Help is very welcome.

**BOT API v7.3:**

- [x] Added support for [InlineKeyboardMarkup](https://core.telegram.org/bots/api#inlinekeyboardmarkup) with url, login_url, and callback_game buttons for messages sent on behalf of a business account.
- [x] Added the field via_join_request to the class [ChatMemberUpdated](https://core.telegram.org/bots/api#chatmemberupdated).
- [x] Added support for live locations that can be edited indefinitely, allowing 0x7FFFFFFF to be used as live_period.
- [x] Added the parameter live_period to the method [editMessageLiveLocation](https://core.telegram.org/bots/api#editmessagelivelocation).
- [x] Added the field question_entities to the class [Poll](https://core.telegram.org/bots/api#poll).
- [x] Added the field text_entities to the class [PollOption](https://core.telegram.org/bots/api#polloption).
- [x] Added the parameters question_parse_mode and question_entities to the method [sendPoll](https://core.telegram.org/bots/api#sendpoll).
- [x] Added the class [InputPollOption](https://core.telegram.org/bots/api#inputpolloption) and changed the type of the parameter options in the method [sendPoll](https://core.telegram.org/bots/api#sendpoll) to Array of [InputPollOption](https://core.telegram.org/bots/api#inputpolloption).
- [x] Added the classes [ChatBackground](https://core.telegram.org/bots/api#chatbackground), [BackgroundType](https://core.telegram.org/bots/api#backgroundtype), [BackgroundFill](https://core.telegram.org/bots/api#backgroundfill) and the field chat_background_set of type [ChatBackground](https://core.telegram.org/bots/api#chatbackground) to the class [Message](https://core.telegram.org/bots/api#message), describing service messages about background changes.
- [x] Split out the class [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo) from the class [Chat](https://core.telegram.org/bots/api#chat) and changed the return type of the method [getChat](https://core.telegram.org/bots/api#getchat) to [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo).
- [x] Added the field max_reaction_count to the class [ChatFullInfo](https://core.telegram.org/bots/api#chatfullinfo).

**BOT API v7.4:**

- [x] Added support for payments in [Telegram Stars](https://t.me/BotNews/90) by introducing the new currency “XTR”.
- [x] The parameter provider_token of the methods [sendInvoice](https://core.telegram.org/bots/api#sendinvoice) and [createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).
- [x] The field provider_token in the class [InputInvoiceMessageContent](https://core.telegram.org/bots/api#inputinvoicemessagecontent) must be omitted for payments in [Telegram Stars](https://t.me/BotNews/90).
- [x] Added the method [refundStarPayment](https://core.telegram.org/bots/api#refundstarpayment).
- [x] Added the field effect_id to the class [Message](https://core.telegram.org/bots/api#message).
- [x] Added the parameter message_effect_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendInvoice](https://core.telegram.org/bots/api#sendinvoice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
- [x] Added the field show_caption_above_media to the classes [Message](https://core.telegram.org/bots/api#message), [InputMediaAnimation](https://core.telegram.org/bots/api#inputmediaanimation), [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto), [InputMediaVideo](https://core.telegram.org/bots/api#inputmediavideo), [InlineQueryResultGif](https://core.telegram.org/bots/api#inlinequeryresultgif), [InlineQueryResultMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultmpeg4gif), [InlineQueryResultPhoto](https://core.telegram.org/bots/api#inlinequeryresultphoto), [InlineQueryResultVideo](https://core.telegram.org/bots/api#inlinequeryresultvideo), [InlineQueryResultCachedGif](https://core.telegram.org/bots/api#inlinequeryresultcachedgif), [InlineQueryResultCachedMpeg4Gif](https://core.telegram.org/bots/api#inlinequeryresultcachedmpeg4gif), [InlineQueryResultCachedPhoto](https://core.telegram.org/bots/api#inlinequeryresultcachedphoto), and [InlineQueryResultCachedVideo](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo).
- [x] Added the parameter show_caption_above_media to the methods [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [copyMessage](https://core.telegram.org/bots/api#copymessage), and [editMessageCaption](https://core.telegram.org/bots/api#editmessagecaption).
- [x] Added support for “expandable_blockquote” entities in received messages.
- [x] Added support for “expandable_blockquote” entity parsing in “MarkdownV2” and “HTML” parse modes.
- [x] Allowed to explicitly specify “expandable_blockquote” entities in formatted texts.

Thanks everyone!

### CODE REVIEW

**Comment by mircoianese** [comment]
I'm not going to write Kotlin classes as I'm a Java user. You are free to convert those if you prefer.
I personally do not like to much the mixing of Java and Kotlin, and it's actually causing me a lot of issues using vscode.

**Comment by mircoianese** [comment]
BOT API v7.3 is ready.

Working on v7.4 in the next days

@pengrad @anfanik

**Comment by mircoianese** [comment]
Pushed a fix for deserialization of sub-classes of BackgroundType and BackgroundFill (API v7.3)

**Comment by mircoianese** [comment]
@pengrad @anfanik Please someone review this, it's quite urgent as there is a breaking change on telegram policies that requires the usage of "XTR" for selling digital services by June 11.
Thanks

**Comment by anfanik** [comment]
I'll check it today

**Review by pengrad — APPROVED** [review]

**Pull request merged**
