### PR TITLE
Java code-style

### PR DESCRIPTION
**Pull request by Pixelase**
Encapsulated fields, added getters and setters, variable names changed to the java-style and a little bit refactoring (sorry for that, i did it from eclipse).
Maybe it's all unnecessary, and so it was planned (public fields, etc.), I do not know.
But I liked your lib, and I decided to embellish it a bit.

### CODE REVIEW

**Comment by pengrad** [comment]
Hi, thanks for your work!
I really wanted to make all this stuff, but decided to make first version this simple.

I consider model classes like immutable data classes, that are created by library and aren't useful outside of request-response scope. But it doesn't mean that getters don't need, especially in the form of messageId(), fileSize(). I think 'get' prefix is redundant here, don't you think so?
About setters - yes, I think they aren't useful for response model objects.

For objects created by user, I wanted to give additional building methods, like this:
markup = new ReplyKeyboardMarkup(keyboards).resize(false).oneTime(false).selective(true);
In this case it's a some kind of setters.

Problem in your patch is that we can't just rename fields, they are auto assigned by Gson deserialization. So, every field with camel case will be null, as Gson try to set field "message_id", not "messageId".
We can solve this by adding Gson naming rules, annotate every field or just keep them with same names, I prefer last one :) With private fields it is especially good as nobody will see the underscores, dealing with getters and setters.

**Comment by Pixelase** [comment]
@pengrad
Hi. I understand the way you think. I saw two types of implementation in other telegram bot api libs on github, like you said: in the first people named every field with camel case and annotate them, in the second fields have the same names like in the telegram api. 
The idea of private fields that have the same names like in the api, but also they have public getters with camel case is good :)

About I 'get' I don't think that it is redundant. Because we after all dealing with the methods and methods should have in its name the verb, I think so.

About additional building methods:
"markup = new ReplyKeyboardMarkup(keyboards).resize(false).oneTime(false).selective(true);"
Yes, it's also good, but I don't know how to implement it in a beautiful way.
Maybe ordinary constructors are more convenient?

But thanks anyway! I will try add annotations to the fields on my fork, maybe it will work.

**Comment by pengrad** [comment]
About getters. 
If we have immutable objects without setters it means we can safely create our getters without 'get'. Just for simplicity. And maybe readability. For example, in case of getting chatId from Update object current version is pretty short: `Integer chatId = update.message.chat.id`
Ok, we don't have properties, so directly using fields it's not good.
With full getters: `Integer chatId = update.getMessage().getChat().getId()`  much noisier.
And with simple getters: `Integer chatId = update.message().chat().id()` – better.

For building methods, we can go like Retrofit Builder. 
```java
keyboard = new ReplyKeyboardMarkup.Builder()
    .keyboard(keyboards)
    .resize(false)
    .oneTime(false)
    .selective(true)
    .build();
```
But I think it's redundant, in our case we don't get object in bad state if forget to init something, that's why we can just use this build methods like setters:

```java
    public ReplyKeyboardMarkup(String[]... keyboard) {
        // constructor with only necessary fields
    }

    public ReplyKeyboardMarkup resize(boolean resize) {
        this.resize = resize;
        return this;
    }
    // and so on ...
```

By the way, there is no getters and setters in new Retrofit 2.0 :)

**Comment by Pixelase** [comment]
Maybe you're right about getters on immutable objects and without 'get' word it will be more readable.
Tomorrow I'll clean the 'get' word from the model's getters.

**Comment by pengrad** [comment]
Hi, I've just implemented everything we discussing here.
So i close this, and you can merge from me :)
If you have time and desire, I'd be very glad if you help me with documentation.

**Comment by Pixelase** [comment]
Ok, no problem.
Good work by the way :)
Waiting for maven release.
I'll try to help with the documentation if I'll have free time.

**Comment by pengrad** [comment]
@Pixelase 
Hi, what do you think the best way to support channels? 
Problem is every "send*" method now takes chat_id as Integer or String (for "@channel"), but we support only integers. Do you have any ideas?

We can simply duplicate every method, for example sendMessage(Integer chatId...) and sendMessage(String channelId...), but it's not fun. 

We can create base class like ChatRecepient, but the problem is how to serialize and deserialize it..

**Comment by Pixelase** [comment]
@pengrad Hi, I don't have any other good ideas.
It is possible, of course, to specify the type of the parameter as Object, but I think it's not a good idea :D

**Pull request closed without merging**
